export const residentialProjects = [
  {
    client: "Mr. Manish",
    location: "Pinjore",
    area: "6500 SQ FT",
    theme: "Modern Luxury",
    status: "Ongoing",
    images: ["/manish.jpeg"],
  },
  {
    client: "Mr. Gursewak Brar",
    location: "Chandigarh",
    area: "5000 SQ FT",
    theme: "Neo Classic",
    status: "Ongoing",
    images: ["/gursewak1.jpeg","/gursewak2.jpeg"],
  },
  // {
  //   client: "Mr. Sehaj",
  //   location: "109 Emaar Mohali",
  //   area: "6000 SQ FT",
  //   theme: "Classic",
  //   status: "Ongoing",
  //   images: ["/res3.jpg"],
  // },
  {
    client: "Mr. Ankit Singla",
    location: "Sector 26 Panchkula",
    area: "5000 SQ FT",
    theme: "Modern",
    status: "Completed",
    images: ["/Ankitsingla.jpeg"],
  },
  {
    client: "Mr. Abhishek Jain",
    location: "Sector 16 Panchkula",
    area: "4000 SQ FT",
    theme: "Modern",
    status: "Ongoing",
    images: ["/abhishek_jain.jpeg"],
  },
  {
    client: "Adv. Kawardeep Singh",
    location: "Sector 27 Panchkula",
    area: "13000 SQ FT",
    theme: "Classic",
    status: "Ongoing",
    images: ["/kawardeep1.JPG","/kawardeep2.jpeg"],
  },
  {
    client: "Prof. Maninder Singh",
    location: "New Chandigarh",
    area: "2000 SQ FT",
    theme: "Modern",
    status: "Completed",
    images: ["/maninder.jpeg"],
  },
];